version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_predictions
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/__pycache__
      # 📝 PERSISTENT LOGGING VOLUMES - Logs persist between container restarts
      - ./logs:/app/logs                    # Main logs directory
      - ./logs:/app/backend/logs            # Backend-specific logs
      - backend_logs:/var/log/app           # Additional log location for system logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/football_predictions
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=developmentsecretkey
      - JWT_SECRET_KEY=developmentjwtsecretkey
      - CREATE_TABLES_ON_STARTUP=True
      - CORS_ORIGINS=["http://localhost:3000","http://127.0.0.1:3000","http://0.0.0.0:3000","http://frontend:3000"]
      - CORS_ALLOW_CREDENTIALS=true
      - CORS_ALLOW_METHODS=["GET","POST","PUT","DELETE","OPTIONS","PATCH"]
      - CORS_ALLOW_HEADERS=["*"]
      - CORS_EXPOSE_HEADERS=["X-RateLimit-Limit","X-RateLimit-Remaining","X-RateLimit-Reset"]
      - API_RATE_LIMIT=600
      - FOOTBALL_API_KEY=2e229688fb1a199c6243f07a2b6e4b54
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules from host
      - /app/dist          # Exclude dist folder
      # 📝 FRONTEND LOGS (if you want frontend logging too)
      - ./logs/frontend:/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_ENV=development
      - API_PROXY=http://backend:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    command: npm start
    stdin_open: true  # Keep STDIN open for React
    tty: true        # Allocate a pseudo-TTY
    networks:
      - app-network

volumes:
  postgres_data:
  # 📝 PERSISTENT LOG VOLUMES
  backend_logs:
    driver: local

networks:
  app-network:
    driver: bridge 