version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_predictions
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/football_predictions
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=developmentsecretkey
      - JWT_SECRET_KEY=developmentjwtsecretkey
      - CREATE_TABLES_ON_STARTUP=True
      - CORS_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:8000/api/v1

volumes:
  postgres_data: