# railway.toml - Monorepo configuration with multiple services

# Backend service
[[services]]
name = "backend"
source = "backend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[services.deploy]
startCommand = "gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

# Frontend service  
[[services]]
name = "frontend"
source = "frontend"

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.prod"

[services.deploy]
startCommand = "nginx -g 'daemon off;'"